// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package retellai.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the RetellAi module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder callDataContextBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("RetellAi.CallDataContext");
		return builder;
	}

	public static java.lang.String callDataContext(IContext context)
	{
		Object result = callDataContextBuilder().execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder checkConfigurationBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("RetellAi.CheckConfiguration");
		return builder;
	}

	public static void checkConfiguration(IContext context)
	{
		checkConfigurationBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder retell_CreateWebCallBuilder(
		java.lang.String _agentPrompt,
		java.lang.String _beginPhrase
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("RetellAi.Retell_CreateWebCall");
		builder = builder.withParam("AgentPrompt", _agentPrompt);
		builder = builder.withParam("BeginPhrase", _beginPhrase);
		return builder;
	}

	public static java.lang.String retell_CreateWebCall(
		IContext context,
		java.lang.String _agentPrompt,
		java.lang.String _beginPhrase
	)
	{
		Object result = retell_CreateWebCallBuilder(
				_agentPrompt,
				_beginPhrase
			)
			.execute(context);
		return (java.lang.String) result;
	}
}
