// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package retellai.proxies;

public class Retell_llm_dynamic_variables implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject retell_llm_dynamic_variablesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "RetellAi.Retell_llm_dynamic_variables";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AgentPrompt("AgentPrompt"),
		BeginMessage("BeginMessage"),
		Retell_llm_dynamic_variables_RetellAI_CallRequest("RetellAi.Retell_llm_dynamic_variables_RetellAI_CallRequest");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Retell_llm_dynamic_variables(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Retell_llm_dynamic_variables(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject retell_llm_dynamic_variablesMendixObject)
	{
		if (retell_llm_dynamic_variablesMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, retell_llm_dynamic_variablesMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.retell_llm_dynamic_variablesMendixObject = retell_llm_dynamic_variablesMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static retellai.proxies.Retell_llm_dynamic_variables initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new retellai.proxies.Retell_llm_dynamic_variables(context, mendixObject);
	}

	public static retellai.proxies.Retell_llm_dynamic_variables load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return retellai.proxies.Retell_llm_dynamic_variables.initialize(context, mendixObject);
	}

	/**
	 * @return value of AgentPrompt
	 */
	public final java.lang.String getAgentPrompt()
	{
		return getAgentPrompt(getContext());
	}

	/**
	 * @param context
	 * @return value of AgentPrompt
	 */
	public final java.lang.String getAgentPrompt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AgentPrompt.toString());
	}

	/**
	 * Set value of AgentPrompt
	 * @param agentprompt
	 */
	public final void setAgentPrompt(java.lang.String agentprompt)
	{
		setAgentPrompt(getContext(), agentprompt);
	}

	/**
	 * Set value of AgentPrompt
	 * @param context
	 * @param agentprompt
	 */
	public final void setAgentPrompt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String agentprompt)
	{
		getMendixObject().setValue(context, MemberNames.AgentPrompt.toString(), agentprompt);
	}

	/**
	 * @return value of BeginMessage
	 */
	public final java.lang.String getBeginMessage()
	{
		return getBeginMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of BeginMessage
	 */
	public final java.lang.String getBeginMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BeginMessage.toString());
	}

	/**
	 * Set value of BeginMessage
	 * @param beginmessage
	 */
	public final void setBeginMessage(java.lang.String beginmessage)
	{
		setBeginMessage(getContext(), beginmessage);
	}

	/**
	 * Set value of BeginMessage
	 * @param context
	 * @param beginmessage
	 */
	public final void setBeginMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String beginmessage)
	{
		getMendixObject().setValue(context, MemberNames.BeginMessage.toString(), beginmessage);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Retell_llm_dynamic_variables_RetellAI_CallRequest
	 */
	public final retellai.proxies.RetellAI_CallRequest getRetell_llm_dynamic_variables_RetellAI_CallRequest() throws com.mendix.core.CoreException
	{
		return getRetell_llm_dynamic_variables_RetellAI_CallRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of Retell_llm_dynamic_variables_RetellAI_CallRequest
	 * @throws com.mendix.core.CoreException
	 */
	public final retellai.proxies.RetellAI_CallRequest getRetell_llm_dynamic_variables_RetellAI_CallRequest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		retellai.proxies.RetellAI_CallRequest result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Retell_llm_dynamic_variables_RetellAI_CallRequest.toString());
		if (identifier != null) {
			result = retellai.proxies.RetellAI_CallRequest.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Retell_llm_dynamic_variables_RetellAI_CallRequest
	 * @param retell_llm_dynamic_variables_retellai_callrequest
	 */
	public final void setRetell_llm_dynamic_variables_RetellAI_CallRequest(retellai.proxies.RetellAI_CallRequest retell_llm_dynamic_variables_retellai_callrequest)
	{
		setRetell_llm_dynamic_variables_RetellAI_CallRequest(getContext(), retell_llm_dynamic_variables_retellai_callrequest);
	}

	/**
	 * Set value of Retell_llm_dynamic_variables_RetellAI_CallRequest
	 * @param context
	 * @param retell_llm_dynamic_variables_retellai_callrequest
	 */
	public final void setRetell_llm_dynamic_variables_RetellAI_CallRequest(com.mendix.systemwideinterfaces.core.IContext context, retellai.proxies.RetellAI_CallRequest retell_llm_dynamic_variables_retellai_callrequest)
	{
		if (retell_llm_dynamic_variables_retellai_callrequest == null) {
			getMendixObject().setValue(context, MemberNames.Retell_llm_dynamic_variables_RetellAI_CallRequest.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Retell_llm_dynamic_variables_RetellAI_CallRequest.toString(), retell_llm_dynamic_variables_retellai_callrequest.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return retell_llm_dynamic_variablesMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final retellai.proxies.Retell_llm_dynamic_variables that = (retellai.proxies.Retell_llm_dynamic_variables) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
