// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package retellai.proxies;

public class RetellAI_CallResponse implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject retellAI_CallResponseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "RetellAi.RetellAI_CallResponse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Call_id("Call_id"),
		Agent_id("Agent_id"),
		Call_status("Call_status"),
		Access_token("Access_token");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RetellAI_CallResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected RetellAI_CallResponse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject retellAI_CallResponseMendixObject)
	{
		if (retellAI_CallResponseMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, retellAI_CallResponseMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.retellAI_CallResponseMendixObject = retellAI_CallResponseMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static retellai.proxies.RetellAI_CallResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new retellai.proxies.RetellAI_CallResponse(context, mendixObject);
	}

	public static retellai.proxies.RetellAI_CallResponse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return retellai.proxies.RetellAI_CallResponse.initialize(context, mendixObject);
	}

	/**
	 * @return value of Call_id
	 */
	public final java.lang.String getCall_id()
	{
		return getCall_id(getContext());
	}

	/**
	 * @param context
	 * @return value of Call_id
	 */
	public final java.lang.String getCall_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Call_id.toString());
	}

	/**
	 * Set value of Call_id
	 * @param call_id
	 */
	public final void setCall_id(java.lang.String call_id)
	{
		setCall_id(getContext(), call_id);
	}

	/**
	 * Set value of Call_id
	 * @param context
	 * @param call_id
	 */
	public final void setCall_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String call_id)
	{
		getMendixObject().setValue(context, MemberNames.Call_id.toString(), call_id);
	}

	/**
	 * @return value of Agent_id
	 */
	public final java.lang.String getAgent_id()
	{
		return getAgent_id(getContext());
	}

	/**
	 * @param context
	 * @return value of Agent_id
	 */
	public final java.lang.String getAgent_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Agent_id.toString());
	}

	/**
	 * Set value of Agent_id
	 * @param agent_id
	 */
	public final void setAgent_id(java.lang.String agent_id)
	{
		setAgent_id(getContext(), agent_id);
	}

	/**
	 * Set value of Agent_id
	 * @param context
	 * @param agent_id
	 */
	public final void setAgent_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String agent_id)
	{
		getMendixObject().setValue(context, MemberNames.Agent_id.toString(), agent_id);
	}

	/**
	 * @return value of Call_status
	 */
	public final java.lang.String getCall_status()
	{
		return getCall_status(getContext());
	}

	/**
	 * @param context
	 * @return value of Call_status
	 */
	public final java.lang.String getCall_status(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Call_status.toString());
	}

	/**
	 * Set value of Call_status
	 * @param call_status
	 */
	public final void setCall_status(java.lang.String call_status)
	{
		setCall_status(getContext(), call_status);
	}

	/**
	 * Set value of Call_status
	 * @param context
	 * @param call_status
	 */
	public final void setCall_status(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String call_status)
	{
		getMendixObject().setValue(context, MemberNames.Call_status.toString(), call_status);
	}

	/**
	 * @return value of Access_token
	 */
	public final java.lang.String getAccess_token()
	{
		return getAccess_token(getContext());
	}

	/**
	 * @param context
	 * @return value of Access_token
	 */
	public final java.lang.String getAccess_token(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Access_token.toString());
	}

	/**
	 * Set value of Access_token
	 * @param access_token
	 */
	public final void setAccess_token(java.lang.String access_token)
	{
		setAccess_token(getContext(), access_token);
	}

	/**
	 * Set value of Access_token
	 * @param context
	 * @param access_token
	 */
	public final void setAccess_token(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String access_token)
	{
		getMendixObject().setValue(context, MemberNames.Access_token.toString(), access_token);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return retellAI_CallResponseMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final retellai.proxies.RetellAI_CallResponse that = (retellai.proxies.RetellAI_CallResponse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
