// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package retellai.proxies;

public class RetellAI_CallRequest implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject retellAI_CallRequestMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "RetellAi.RetellAI_CallRequest";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Agent_id("Agent_id"),
		Retell_llm_dynamic_variables_RetellAI_CallRequest("RetellAi.Retell_llm_dynamic_variables_RetellAI_CallRequest");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RetellAI_CallRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected RetellAI_CallRequest(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject retellAI_CallRequestMendixObject)
	{
		if (retellAI_CallRequestMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, retellAI_CallRequestMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.retellAI_CallRequestMendixObject = retellAI_CallRequestMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static retellai.proxies.RetellAI_CallRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new retellai.proxies.RetellAI_CallRequest(context, mendixObject);
	}

	public static retellai.proxies.RetellAI_CallRequest load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return retellai.proxies.RetellAI_CallRequest.initialize(context, mendixObject);
	}

	/**
	 * @return value of Agent_id
	 */
	public final java.lang.String getAgent_id()
	{
		return getAgent_id(getContext());
	}

	/**
	 * @param context
	 * @return value of Agent_id
	 */
	public final java.lang.String getAgent_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Agent_id.toString());
	}

	/**
	 * Set value of Agent_id
	 * @param agent_id
	 */
	public final void setAgent_id(java.lang.String agent_id)
	{
		setAgent_id(getContext(), agent_id);
	}

	/**
	 * Set value of Agent_id
	 * @param context
	 * @param agent_id
	 */
	public final void setAgent_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String agent_id)
	{
		getMendixObject().setValue(context, MemberNames.Agent_id.toString(), agent_id);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Retell_llm_dynamic_variables_RetellAI_CallRequest
	 */
	public final retellai.proxies.Retell_llm_dynamic_variables getRetell_llm_dynamic_variables_RetellAI_CallRequest() throws com.mendix.core.CoreException
	{
		return getRetell_llm_dynamic_variables_RetellAI_CallRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of Retell_llm_dynamic_variables_RetellAI_CallRequest
	 * @throws com.mendix.core.CoreException
	 */
	public final retellai.proxies.Retell_llm_dynamic_variables getRetell_llm_dynamic_variables_RetellAI_CallRequest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		retellai.proxies.Retell_llm_dynamic_variables result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Retell_llm_dynamic_variables_RetellAI_CallRequest.toString());
		if (identifier != null) {
			result = retellai.proxies.Retell_llm_dynamic_variables.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Retell_llm_dynamic_variables_RetellAI_CallRequest
	 * @param retell_llm_dynamic_variables_retellai_callrequest
	 */
	public final void setRetell_llm_dynamic_variables_RetellAI_CallRequest(retellai.proxies.Retell_llm_dynamic_variables retell_llm_dynamic_variables_retellai_callrequest)
	{
		setRetell_llm_dynamic_variables_RetellAI_CallRequest(getContext(), retell_llm_dynamic_variables_retellai_callrequest);
	}

	/**
	 * Set value of Retell_llm_dynamic_variables_RetellAI_CallRequest
	 * @param context
	 * @param retell_llm_dynamic_variables_retellai_callrequest
	 */
	public final void setRetell_llm_dynamic_variables_RetellAI_CallRequest(com.mendix.systemwideinterfaces.core.IContext context, retellai.proxies.Retell_llm_dynamic_variables retell_llm_dynamic_variables_retellai_callrequest)
	{
		if (retell_llm_dynamic_variables_retellai_callrequest == null) {
			getMendixObject().setValue(context, MemberNames.Retell_llm_dynamic_variables_RetellAI_CallRequest.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Retell_llm_dynamic_variables_RetellAI_CallRequest.toString(), retell_llm_dynamic_variables_retellai_callrequest.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return retellAI_CallRequestMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final retellai.proxies.RetellAI_CallRequest that = (retellai.proxies.RetellAI_CallRequest) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
