// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package feedbackmodule.proxies;

public enum TranslationLanguages
{
	Dutch(new java.lang.String[][] { new java.lang.String[] { "en_US", "Dutch" }, new java.lang.String[] { "pt_BR", "holandês" } }),
	English(new java.lang.String[][] { new java.lang.String[] { "en_US", "English" }, new java.lang.String[] { "pt_BR", "Inglês" } }),
	French(new java.lang.String[][] { new java.lang.String[] { "en_US", "French" }, new java.lang.String[] { "pt_BR", "francês" } }),
	German(new java.lang.String[][] { new java.lang.String[] { "en_US", "German" }, new java.lang.String[] { "pt_BR", "alemã" } }),
	Hindi(new java.lang.String[][] { new java.lang.String[] { "en_US", "Hindi" }, new java.lang.String[] { "pt_BR", "hindi" } }),
	Portuguese(new java.lang.String[][] { new java.lang.String[] { "en_US", "Portuguese" }, new java.lang.String[] { "pt_BR", "portuguesa" } }),
	Spanish(new java.lang.String[][] { new java.lang.String[] { "en_US", "Spanish" }, new java.lang.String[] { "pt_BR", "espanhol" } }),
	Turkish(new java.lang.String[][] { new java.lang.String[] { "en_US", "Turkish" }, new java.lang.String[] { "pt_BR", "turca" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private TranslationLanguages(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "pt_BR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("pt_BR");
	}
}
