// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class BankAccount implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject bankAccountMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.BankAccount";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AccountType("AccountType"),
		Balance("Balance"),
		BankAccount_Customer("MyFirstModule.BankAccount_Customer");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public BankAccount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected BankAccount(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject bankAccountMendixObject)
	{
		if (bankAccountMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, bankAccountMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.bankAccountMendixObject = bankAccountMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.BankAccount initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.BankAccount(context, mendixObject);
	}

	public static myfirstmodule.proxies.BankAccount load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.BankAccount.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.BankAccount> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.BankAccount.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Get value of AccountType
	 * @param accounttype
	 */
	public final myfirstmodule.proxies.Customer_Types getAccountType()
	{
		return getAccountType(getContext());
	}

	/**
	 * @param context
	 * @return value of AccountType
	 */
	public final myfirstmodule.proxies.Customer_Types getAccountType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.AccountType.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Customer_Types.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of AccountType
	 * @param accounttype
	 */
	public final void setAccountType(myfirstmodule.proxies.Customer_Types accounttype)
	{
		setAccountType(getContext(), accounttype);
	}

	/**
	 * Set value of AccountType
	 * @param context
	 * @param accounttype
	 */
	public final void setAccountType(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Customer_Types accounttype)
	{
		if (accounttype != null) {
			getMendixObject().setValue(context, MemberNames.AccountType.toString(), accounttype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.AccountType.toString(), null);
		}
	}

	/**
	 * @return value of Balance
	 */
	public final java.math.BigDecimal getBalance()
	{
		return getBalance(getContext());
	}

	/**
	 * @param context
	 * @return value of Balance
	 */
	public final java.math.BigDecimal getBalance(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Balance.toString());
	}

	/**
	 * Set value of Balance
	 * @param balance
	 */
	public final void setBalance(java.math.BigDecimal balance)
	{
		setBalance(getContext(), balance);
	}

	/**
	 * Set value of Balance
	 * @param context
	 * @param balance
	 */
	public final void setBalance(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal balance)
	{
		getMendixObject().setValue(context, MemberNames.Balance.toString(), balance);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of BankAccount_Customer
	 */
	public final myfirstmodule.proxies.Customer getBankAccount_Customer() throws com.mendix.core.CoreException
	{
		return getBankAccount_Customer(getContext());
	}

	/**
	 * @param context
	 * @return value of BankAccount_Customer
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Customer getBankAccount_Customer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Customer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BankAccount_Customer.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Customer.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of BankAccount_Customer
	 * @param bankaccount_customer
	 */
	public final void setBankAccount_Customer(myfirstmodule.proxies.Customer bankaccount_customer)
	{
		setBankAccount_Customer(getContext(), bankaccount_customer);
	}

	/**
	 * Set value of BankAccount_Customer
	 * @param context
	 * @param bankaccount_customer
	 */
	public final void setBankAccount_Customer(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Customer bankaccount_customer)
	{
		if (bankaccount_customer == null) {
			getMendixObject().setValue(context, MemberNames.BankAccount_Customer.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.BankAccount_Customer.toString(), bankaccount_customer.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return bankAccountMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.BankAccount that = (myfirstmodule.proxies.BankAccount) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
