// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import "mx-global";

// BEGIN EXTRA CODE
import { RetellWebClient } from "retell-client-js-sdk";
const retellWebClient = new RetellWebClient();

async function startCall(token) {
  try {
    await retellWebClient.startCall({
      accessToken: token,
    });
  } catch (error) {
    console.error("Failed to start conversation:", error);
  }
}

function stopCall() {
  retellWebClient.stopCall();
  console.log("Conversation stopped");
}

// END EXTRA CODE

/**
 * @param {string} token - Token received when you Created the Web Call
 * @param {string} callAction - Start / Stop
 * @returns {Promise.<void>}
 */
export async function Retell(token, callAction) {
	// BEGIN USER CODE
    if (callAction === "Start") {
        await startCall(token);
    } else if (callAction === "Stop") {
        stopCall();
    } else {
        throw new Error("Invalid action parameter. Please use 'Start' or 'Stop'.");
    }
	// END USER CODE
}
