// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains(new java.lang.String[][] { new java.lang.String[] { "en_US", "Contains" }, new java.lang.String[] { "pt_BR", "Contém" } }),
	startsWith(new java.lang.String[][] { new java.lang.String[] { "en_US", "Starts with" }, new java.lang.String[] { "pt_BR", "Começa com" } }),
	endsWith(new java.lang.String[][] { new java.lang.String[] { "en_US", "Ends with" }, new java.lang.String[] { "pt_BR", "Termina com" } }),
	between(new java.lang.String[][] { new java.lang.String[] { "en_US", "Between" }, new java.lang.String[] { "pt_BR", "Entre" } }),
	greater(new java.lang.String[][] { new java.lang.String[] { "en_US", "Greater than" }, new java.lang.String[] { "pt_BR", "Maior que" } }),
	greaterEqual(new java.lang.String[][] { new java.lang.String[] { "en_US", "Greater than or equal" }, new java.lang.String[] { "pt_BR", "Maior ou igual" } }),
	equal(new java.lang.String[][] { new java.lang.String[] { "en_US", "Equal" }, new java.lang.String[] { "pt_BR", "Igual" } }),
	notEqual(new java.lang.String[][] { new java.lang.String[] { "en_US", "Not equal" }, new java.lang.String[] { "pt_BR", "Não é igual" } }),
	smaller(new java.lang.String[][] { new java.lang.String[] { "en_US", "Smaller than" }, new java.lang.String[] { "pt_BR", "Menor que" } }),
	smallerEqual(new java.lang.String[][] { new java.lang.String[] { "en_US", "Smaller than or equal" }, new java.lang.String[] { "pt_BR", "Menor ou igual" } }),
	empty(new java.lang.String[][] { new java.lang.String[] { "en_US", "Empty" }, new java.lang.String[] { "pt_BR", "Vazio" } }),
	notEmpty(new java.lang.String[][] { new java.lang.String[] { "en_US", "Not empty" }, new java.lang.String[] { "pt_BR", "Não está vazio" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private Filter_Operators(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "pt_BR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("pt_BR");
	}
}
